/**
 * Age Checker Callback Verification Service
 *
 * AgeChecker.Net is a CLIENT-SIDE widget — the JS embed handles the UI and
 * verification flow. This service handles server-side concerns:
 *
 *   1. HMAC signature verification for webhook callbacks from AgeChecker
 *   2. Storing age-verification results against orders in our DB
 *
 * Required .env vars:
 *   AGECHECKER_API_KEY=64Tw24wNqoE1MNcvdwYboVpmdpFsv7tZ      (public, also used client-side)
 *   AGECHECKER_ACCOUNT_SECRET=L04KfMS0rCpoaaza               (private, server-side only)
 *   AGECHECKER_SITE=highway420store.com
 */

import crypto from 'crypto';

export interface AgeCheckCallbackPayload {
  /** AgeChecker.Net transaction ID */
  id: string;
  /** 'verified' | 'denied' | 'pending' */
  status: string;
  /** unix timestamp */
  timestamp: number;
  /** HMAC signature for verification */
  signature?: string;
  /** Custom data you passed in the widget config */
  metadata?: Record<string, any>;
}

export interface AgeCheckResult {
  verified: boolean;
  transactionId?: string;
  reason?: string;
}

/**
 * Verify that a callback from AgeChecker.Net is authentic using HMAC-SHA256.
 * The signature is generated by AgeChecker using your Account Secret.
 */
export function verifyAgeCheckerSignature(
  payload: Record<string, any>,
  signature: string
): boolean {
  const secret = process.env.AGECHECKER_ACCOUNT_SECRET;
  if (!secret) {
    console.warn('[AgeChecker] Account secret not set — skipping signature verification');
    return true; // Allow in dev
  }

  const message = JSON.stringify(payload);
  const expected = crypto
    .createHmac('sha256', secret)
    .update(message)
    .digest('hex');

  // Use timingSafeEqual to prevent timing attacks
  try {
    return crypto.timingSafeEqual(
      Buffer.from(expected, 'hex'),
      Buffer.from(signature, 'hex')
    );
  } catch {
    return false;
  }
}

/**
 * Parse and validate an AgeChecker.Net callback payload into a normalized result.
 */
export function parseAgeCheckCallback(payload: AgeCheckCallbackPayload): AgeCheckResult {
  const { signature, ...rest } = payload as any;

  if (signature && !verifyAgeCheckerSignature(rest, signature)) {
    console.error('[AgeChecker] Invalid callback signature — possible tampered payload');
    return { verified: false, reason: 'invalid_signature' };
  }

  const verified = payload.status === 'verified';
  return {
    verified,
    transactionId: payload.id,
    reason: payload.status,
  };
}

/**
 * Generate the AgeChecker.Net widget configuration object.
 * This is passed to the client-side widget via window.ageCheckerConfig.
 */
export function getAgeCheckerWidgetConfig(options?: {
  orderId?: string;
  email?: string;
  callbackUrl?: string;
}) {
  return {
    apiKey: process.env.AGECHECKER_API_KEY,
    site: process.env.AGECHECKER_SITE || 'highway420store.com',
    ...(options?.callbackUrl && { callbackUrl: options.callbackUrl }),
    ...(options?.orderId && { metadata: { orderId: options.orderId, email: options.email } }),
  };
}

/**
 * Verify a transaction ID directly with the AgeChecker.Net API.
 * This is used for server-side validation during the checkout process.
 */
export async function verifyTransactionWithApi(transactionId: string): Promise<AgeCheckResult> {
  const secret = process.env.AGECHECKER_ACCOUNT_SECRET;
  
  if (!secret) {
    console.warn('[AgeChecker] Account secret not set — skipping API verification');
    // In development or if secret is missing, we might want to fail-open or fail-closed.
    // For now, let's assume we need it for production.
    return { verified: true, transactionId, reason: 'unverified_secret_missing' };
  }

  try {
    const response = await fetch(`https://api.agechecker.net/v1/verify?id=${transactionId}`, {
      method: 'GET',
      headers: {
        'X-AgeChecker-Secret': secret,
      },
    });

    if (!response.ok) {
      console.error('[AgeChecker] API verification failed:', response.statusText);
      return { verified: false, reason: `api_error_${response.status}` };
    }

    const data = await response.json();
    return {
      verified: data.status === 'verified',
      transactionId: data.id,
      reason: data.status,
    };
  } catch (error) {
    console.error('[AgeChecker] API fetch error:', error);
    return { verified: false, reason: 'fetch_error' };
  }
}
